baseURL: /
title: Grellyd - Graham L. Brown
languageCode: en-ca
theme: kubo_hugo
disableKinds: [RSS, sitemap]
params:
    AuthorName: Graham L. Brown
    GithubUsername: grellyd
    TwitterUsername: grellyd
    LinkedInUsername: grellyd
    ContactEmail: graham@grellyd.com
    SiteName: Grellyd
    HiddenSections: [xmas, writing, email]
googleAnalytics: UA-127080315-1
buildFuture: true
pluralizelisttitles: false
