package pages

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/grellyd/filelogging/globallogger"
)

const (
	rootPath = "./public"
)

// Page on the disk, in public/ generated by hugo
type Page struct {
	Title  string
	Body   []byte
	File   *os.File
	Ending PageEnding
}

// Load a page
func Load(section string, title string, ending PageEnding) (*Page, error) {
	root, err := os.OpenRoot(rootPath)
	if err != nil {
		return nil, fmt.Errorf("cannot OpenRoot: %s", rootPath)
	}

	filename := fmt.Sprintf("%s/%s.%s", section, title, ending)
	globallogger.Debug(fmt.Sprintf("loading '%s'\n", filename))
	f, err := root.OpenFile(filename, os.O_RDONLY, 0444)
	if err != nil {
		return nil, fmt.Errorf("cannot OpenFile %s: %w", filename, err)
	}

	b := []byte{}
	if _, err := f.Read(b); !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("cannot Read: %w", err)
	}

	return &Page{Title: title, Body: b, File: f}, nil
}

// CheckExistence of a page. Error on failure, nil otherwise
func CheckExistence(sections []string, title string, pending PageEnding) error {
	root, err := os.OpenRoot(rootPath)
	if err != nil {
		return fmt.Errorf("cannot OpenRoot: %s", rootPath)
	}

	elems := append(sections, fmt.Sprintf("%s.%s", title, pending))
	filepath := strings.Join(elems, "/")
	globallogger.Debug(fmt.Sprintf("looking for '%s'\n", filepath))

	_, err = root.Stat(filepath)
	return err
}
