# Workflow for building and deploying my Hugo based site to DigitalOcean
name: Deploy Hugo site and Go Server to DO

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["prd"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Allow one concurrent deployment
concurrency:
  group: "do"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    uses: ./.github/workflows/hugo.yml
          
  # Deployment job
  deploy:
    environment:
      name: tbd
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1