name: Deploy to Prd

on:
  push:
    branches: ["prd"]
  workflow_dispatch:

concurrency:
  group: "prd-deploy"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH
        run: |
          mkdir -p ~/.ssh/
          cd ~/.ssh
          echo "$SSH_PRIVATE_KEY" > id_ed25519
          sudo chmod 0600 id_ed25519
          echo "$SSH_KNOWN_HOSTS" > known_hosts
        env:
          SSH_PRIVATE_KEY: ${{secrets.SA_ID_ED25519}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_PRD_KNOWN_HOSTS}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Redeploy
        run: make remote/deploy/prd